#!/bin/bash

# input: ./new_post topic name
# output: _drafts/topic-name.markdown

topic_name=$@
file_name=`echo _drafts/$topic_name.markdown | sed 's/\s/-/g'`
touch $file_name

cat <<-EOF > $file_name
---
layout: post
category : test
tags : []
---
{% include JB/setup %}

EOF
