#!/bin/bash

# input: ./new_post topic name
# output: _posts/current-date-topic-name.markdown

topic_name=$@
creation_date=`date +%Y-%m-%d`
file_name=`echo _posts/$creation_date-$topic_name.markdown | sed 's/\s/-/g'`
touch $file_name

cat <<-EOF > $file_name
---
layout: post
category : test
comments : true
tags : []
---
{% include JB/setup %}

EOF
