#!/bin/bash

# input: ./new_post topic name
# output: _drafts/topic-name.markdown

topic_name=$@
short_name=`echo $topic_name | tr ' ' -`
file_name=_drafts/$short_name.markdown
touch $file_name

cat <<-EOF > $file_name
---
layout: post
category : test
tags : []
---

EOF
