#!/bin/bash

# input: ./today _posts/1970-01-01-some-post.markdown
# output: _posts/current-date-some-post.markdown

old_filename=$1
today=`date +%Y-%m-%d`
new_filename=`echo $old_filename | cut -c 18-`

git mv $old_filename _posts/$today$new_filename
